/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import static assignment.Cars.editRecord;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leelynnchanel
 */
public class ConfirmPayment extends javax.swing.JFrame {
    Path filePath = Paths.get(".", "CustomerData.txt");
    Path filePath2 = Paths.get(".", "cars.txt");


    /**
     * Creates new form Payment
     */
    public ConfirmPayment() {
        initComponents();
    }
    
     public ConfirmPayment(String reg, String carType, String pickUp, String drop, Double total, String username) {
        initComponents();
        lblUser.setText(username);
        cartypeTxt.setText(carType);
        carregTxt.setText(reg);
        pickupTxt.setText(pickUp);
        dropTxt.setText(drop);
        totalTxt.setText(total.toString());
        
        try {
            BufferedReader br = Files.newBufferedReader(filePath);
            Object[] Lines = br.lines().toArray();
            int i = 0;
            for (i = 0; i < Lines.length; i ++){
                String Line = Lines[i].toString().trim();
                String[] Row = Line.split(",");
                System.out.println("row = "+ Row[1]);
                System.out.println("line = "+Line);
                if (username.equals(Row[1])) {
                    fullnameLbl1.setText(Row[0]);
                    emailLbl1.setText(Row[2]);
                    numberLbl1.setText(Row[3]);
                }
            } 
        } catch (Exception ex) {
                ex.printStackTrace();
        } 
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fullnameLbl = new javax.swing.JLabel();
        numberLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        emailLbl1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullnameLbl1 = new javax.swing.JLabel();
        numberLbl1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        radioAgree = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        dropTxt = new javax.swing.JLabel();
        carregTxt = new javax.swing.JLabel();
        pickupTxt = new javax.swing.JLabel();
        totalTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cartypeTxt = new javax.swing.JLabel();

        emailLbl.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        emailLbl.setText("Full name:");

        jLabel13.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        jLabel14.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel14.setText("Mobile Number:");

        jLabel21.setBackground(new java.awt.Color(153, 102, 0));
        jLabel21.setFont(new java.awt.Font("Kohinoor Bangla", 1, 18)); // NOI18N
        jLabel21.setText("Customer Details");

        jLabel1.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel1.setText("Full name:");

        fullnameLbl.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        fullnameLbl.setText("Full name:");

        numberLbl.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        numberLbl.setText("Full name:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(201, 189, 164));

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/leelynnchanel/Desktop/3rd Semester/Java/Group30(TP066765_TP064387)/carrentallogo_copy-removebg-preview copy.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        emailLbl1.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        emailLbl1.setText("Full name:");
        getContentPane().add(emailLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 169, -1, -1));

        jLabel15.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel15.setText("Email:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 171, -1, -1));

        jLabel16.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel16.setText("Mobile Number:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 213, -1, -1));

        jLabel22.setBackground(new java.awt.Color(153, 102, 0));
        jLabel22.setFont(new java.awt.Font("Kohinoor Bangla", 1, 18)); // NOI18N
        jLabel22.setText("Customer Details");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 71, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel2.setText("Full name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 129, -1, -1));

        fullnameLbl1.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        fullnameLbl1.setText("Full name:");
        getContentPane().add(fullnameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 129, -1, -1));

        numberLbl1.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        numberLbl1.setText("Full name:");
        getContentPane().add(numberLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Kohinoor Telugu", 1, 14)); // NOI18N
        jLabel9.setText("Total:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel3.setText("Pick up date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel4.setText("Drop off date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel23.setBackground(new java.awt.Color(153, 102, 0));
        jLabel23.setFont(new java.awt.Font("Kohinoor Bangla", 1, 18)); // NOI18N
        jLabel23.setText("Car Details");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel6.setText("Car registration number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel10.setText("Payment Method:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));

        jLabel11.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel11.setText("Card type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mastercard", "Visa", "American Express", "None", " " }));

        radioAgree.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        radioAgree.setText("I agree with the terms and conditions");
        radioAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAgreeActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("A fine of RM100 per day will be imposed if car is not returned upon due date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioAgree)
                    .addComponent(jLabel5))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(radioAgree)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        getContentPane().add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, -1, -1));

        dropTxt.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        dropTxt.setText("Car type:");
        getContentPane().add(dropTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, -1, -1));

        carregTxt.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        carregTxt.setText("Car type:");
        getContentPane().add(carregTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        pickupTxt.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        pickupTxt.setText("Car type:");
        getContentPane().add(pickupTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        totalTxt.setFont(new java.awt.Font("Kohinoor Telugu", 1, 14)); // NOI18N
        totalTxt.setText("Total:");
        getContentPane().add(totalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setText("Welcome back, ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 15, -1, -1));

        lblUser.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblUser.setText("Welcome back, ");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 15, -1, -1));

        jLabel17.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        jLabel17.setText("Car type:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        cartypeTxt.setFont(new java.awt.Font("Kohinoor Telugu", 0, 14)); // NOI18N
        cartypeTxt.setText("Car type:");
        getContentPane().add(cartypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAgreeActionPerformed

    }//GEN-LAST:event_radioAgreeActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (!radioAgree.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Please agree with the terms and conditions to proceed.");
        } else{
            
            try {
                String fine = "0";
                String total = totalTxt.getText();
                int found;
                FileWriter Writer1 = new FileWriter("RentalBooking.txt", true);
                
                NewBooking newBooking = new NewBooking(carregTxt.getText(), lblUser.getText(),fullnameLbl1.getText(), emailLbl1.getText(), numberLbl1.getText(), cartypeTxt.getText(), pickupTxt.getText(), dropTxt.getText());
                
                Writer1.write(newBooking.getReg() + ","  + newBooking.getCar()+ "," + newBooking.getPick() + "," + newBooking.getDrop() + "," + total + "," + fine + "," + newBooking.getUsername() + "," + newBooking.getName() +","+newBooking.getEmail()+","+newBooking.getNum());
                Writer1.write(System.getProperty("line.separator"));
                
              BufferedReader reader = Files.newBufferedReader(filePath2);
              String line;
               while ((line = reader.readLine()) != null) {
                  String[] fields = line.split("[,]");  
                  if (newBooking.getReg().equals(fields[0])){
                      found = 1;
                     String regnum = fields[0];
                     String brand = fields[1];
                     String Model = fields[2];
                     String status = "Booked";
                     String price = fields[4];
                     
                     editRecord(regnum, brand, Model, status, price, found);
                    if (found == 0)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Record not found.");
                        }
                  }
                    
               }

                Writer1.close();
            } catch (IOException ex) {
                Logger.getLogger(ConfirmPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(rootPane, "Payment successful. The rental car is ready to be collected.");

            new PurchaseHistory(lblUser.getText()).setVisible(true);
            this.setVisible(false);
            new CarBooking().setVisible(false);
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String un = lblUser.getText();
        new CarBooking(un).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel carregTxt;
    private javax.swing.JLabel cartypeTxt;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel dropTxt;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailLbl1;
    private javax.swing.JLabel fullnameLbl;
    private javax.swing.JLabel fullnameLbl1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel numberLbl;
    private javax.swing.JLabel numberLbl1;
    private javax.swing.JLabel pickupTxt;
    private javax.swing.JRadioButton radioAgree;
    private javax.swing.JLabel totalTxt;
    // End of variables declaration//GEN-END:variables
}
